name: Parkstatus Ohlsdorf

on:
  schedule:
    - cron: '15 18 * * *'  # 20:15 Uhr MESZ
    - cron: '16 18 * * *'  # 20:16 Uhr MESZ
    - cron: '17 18 * * *'  # 20:17 Uhr MESZ
    - cron: '18 18 * * *'  # 20:18 Uhr MESZ
  workflow_dispatch:

jobs:
  erfassen:
    # Bedingung entfernt für manuellen Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installiere Abhängigkeiten
        run: pip install requests

      - name: Parkdaten erfassen
        run: |
          CRON_EXPR="${{ github.event.schedule }}"
          case $CRON_EXPR in
            "15 18 * * *") FILE="1501.txt" ;;
            "16 18 * * *") FILE="1502.txt" ;;
            "17 18 * * *") FILE="1503.txt" ;;
            *) FILE="manual-test.txt" ;;
          esac

          DATA=$(curl -s 'https://www.pr.hamburg/ws/ws.get.status.php?obj=173')
          FREE=$(echo $DATA | grep -oP '"free"\s*:\s*\K\d+')
          echo "$FREE" > "$FILE"

      - name: Speichere Datei als Artifact
        uses: actions/upload-artifact@v4
        with:
          name: parkstatus
          path: "*.txt"

  mailversand:
    # Bedingung entfernt für manuellen Test
    needs: erfassen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installiere Abhängigkeiten
        run: pip install requests

      - name: Lade Dateien aus vorherigen Jobs
        uses: actions/download-artifact@v4
        with:
          name: parkstatus

      - name: Lade Parkdaten und bereite Nachricht vor
        id: load
        run: |
          free_530=$(cat 1501.txt 2>/dev/null || echo "-1")
          free_600=$(cat 1502.txt 2>/dev/null || echo "-1")
          free_630=$(cat 1503.txt 2>/dev/null || echo "-1")
          echo "free_530=$free_530" >> $GITHUB_OUTPUT
          echo "free_600=$free_600" >> $GITHUB_OUTPUT
          echo "free_630=$free_630" >> $GITHUB_OUTPUT

      - name: Datum bestimmen
        id: datum
        run: echo "today=$(date '+%d.%m.%Y')" >> $GITHUB_OUTPUT

      - name: E-Mail senden
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port:    ${{ secrets.SMTP_PORT }}
          username:       ${{ secrets.SMTP_USERNAME }}
          password:       ${{ secrets.SMTP_PASSWORD }}
          subject:        "Parkstatus Ohlsdorf am ${{ steps.datum.outputs.today }}"
          to:             ${{ secrets.EMAIL_TO }}
          from:           ${{ secrets.EMAIL_FROM }}
          body: |
            Guten Nachmittag,

            hier die Parkbelegung an der P+R-Anlage Ohlsdorf:

            – Um 20:15 Uhr: ${{ steps.load.outputs.free_530 }} freie Plätze
            – Um 20:16 Uhr: ${{ steps.load.outputs.free_600 }} freie Plätze
            – Um 20:17 Uhr: ${{ steps.load.outputs.free_630 }} freie Plätze

            Viele Grüße!

      - name: Lösche temporäre Dateien
        run: rm *.txt || true
