name: "P+R Ohlsdorf Status mit E-Mail"

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  fetch-and-mail:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install --no-cache -r requirements.txt

      - id: status
        run: |
          output=$(python3 ohlsdorf_status_ws.py)
          echo "$output"
          echo "free=$(echo "$output" | grep 'freie Stellplätze' | awk '{print $4}')" >> $GITHUB_OUTPUT
          echo "used=$(echo "$output" | grep 'belegte Stellplätze' | awk '{print $4}')" >> $GITHUB_OUTPUT

      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port:    ${{ secrets.SMTP_PORT }}
          username:       ${{ secrets.SMTP_USERNAME }}
          password:       ${{ secrets.SMTP_PASSWORD }}
          subject:        "Ohlsdorf P+R-Status am ${{ github.event.date || github.run_started_at }}"
          to:             ${{ secrets.EMAIL_TO }}
          from:           ${{ secrets.EMAIL_FROM }}
          body:           |
            Guten Morgen,

            hier die aktuellen Zahlen der P+R-Anlage Ohlsdorf:

            – Freie Stellplätze: ${{ steps.status.outputs.free }}
            – Belegte Stellplätze: ${{ steps.status.outputs.used }}

            Viele Grüße!
