name: Parkstatus Ohlsdorf

on:
  schedule:
    - cron: '30 3 * * *'  # 05:30 Uhr (UTC)
    - cron: '0 4 * * *'   # 06:00 Uhr (UTC)
    - cron: '30 4 * * *'  # 06:30 Uhr (UTC)
    - cron: '31 4 * * *'  # 06:31 Uhr (UTC)
  workflow_dispatch:

jobs:
  erfassen:
    if: github.event.schedule != '31 4 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installiere Abhängigkeiten
        run: pip install requests

      - name: Parkdaten erfassen
        run: |
          HOUR=$(date +"%H%M")
          DATA=$(curl -s 'https://www.pr.hamburg/ws/ws.get.status.php?obj=173')
          FREE=$(echo $DATA | grep -oP '"free"\s*:\s*\K\d+')
          echo "$FREE" > ${HOUR}.txt

      - name: Commit Datei
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.txt
          git commit -m "Parkdaten gespeichert"
          git push

  mailversand:
    if: github.event.schedule == '31 4 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installiere Abhängigkeiten
        run: pip install requests

      - name: Lade Parkdaten und bereite Nachricht vor
        id: load
        run: |
          free_530=$(cat 0530.txt)
          free_600=$(cat 0600.txt)
          free_630=$(cat 0630.txt)
          echo "free_530=$free_530" >> $GITHUB_OUTPUT
          echo "free_600=$free_600" >> $GITHUB_OUTPUT
          echo "free_630=$free_630" >> $GITHUB_OUTPUT

      - name: Datum bestimmen
        id: datum
        run: echo "today=$(date '+%d.%m.%Y')" >> $GITHUB_OUTPUT

      - name: E-Mail senden
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port:    ${{ secrets.SMTP_PORT }}
          username:       ${{ secrets.SMTP_USERNAME }}
          password:       ${{ secrets.SMTP_PASSWORD }}
          subject:        "Parkstatus Ohlsdorf am ${{ steps.datum.outputs.today }}"
          to:             ${{ secrets.EMAIL_TO }}
          from:           ${{ secrets.EMAIL_FROM }}
          body: |
            Guten Morgen,

            hier die Parkbelegung an der P+R-Anlage Ohlsdorf:

            – Um 05:30 Uhr: ${{ steps.load.outputs.free_530 }} freie Plätze
            – Um 06:00 Uhr: ${{ steps.load.outputs.free_600 }} freie Plätze
            – Um 06:30 Uhr: ${{ steps.load.outputs.free_630 }} freie Plätze

            Viele Grüße!

      - name: Lösche temporäre Dateien
        run: rm 0530.txt 0600.txt 0630.txt
