name: Parkstatus Ohlsdorf

on:
  schedule:
    - cron: '1 13 * * *'  # 15:01 Uhr (UTC)
    - cron: '2 13 * * *'  # 15:02 Uhr (UTC)
    - cron: '3 13 * * *'  # 15:03 Uhr (UTC)
    - cron: '4 13 * * *'  # 15:04 Uhr (UTC)
  workflow_dispatch:

jobs:
  erfassen:
    if: github.event.schedule != '4 13 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installiere Abhängigkeiten
        run: pip install requests

      - name: Parkdaten erfassen
        run: |
          CRON_EXPR="${{ github.event.schedule }}"
          case "$CRON_EXPR" in
            "1 13 * * *") FILE="1501.txt" ;;
            "2 13 * * *") FILE="1502.txt" ;;
            "3 13 * * *") FILE="1503.txt" ;;
            *) echo "Unbekannter Zeitplan: $CRON_EXPR"; exit 1 ;;
          esac

          DATA=$(curl -s 'https://www.pr.hamburg/ws/ws.get.status.php?obj=173')
          FREE=$(echo $DATA | grep -oP '"free"\s*:\s*\K\d+')
          echo "$FREE" > "$FILE"

      - name: Commit Datei
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.txt
          git commit -m "Parkdaten gespeichert"
          git push

  mailversand:
    if: github.event.schedule == '4 13 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installiere Abhängigkeiten
        run: pip install requests

      - name: Lade Parkdaten und bereite Nachricht vor
        id: load
        run: |
          free_530=$(cat 1501.txt)
          free_600=$(cat 1502.txt)
          free_630=$(cat 1503.txt)
          echo "free_530=$free_530" >> $GITHUB_OUTPUT
          echo "free_600=$free_600" >> $GITHUB_OUTPUT
          echo "free_630=$free_630" >> $GITHUB_OUTPUT

      - name: Datum bestimmen
        id: datum
        run: echo "today=$(date '+%d.%m.%Y')" >> $GITHUB_OUTPUT

      - name: E-Mail senden
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port:    ${{ secrets.SMTP_PORT }}
          username:       ${{ secrets.SMTP_USERNAME }}
          password:       ${{ secrets.SMTP_PASSWORD }}
          subject:        "Parkstatus Ohlsdorf am ${{ steps.datum.outputs.today }}"
          to:             ${{ secrets.EMAIL_TO }}
          from:           ${{ secrets.EMAIL_FROM }}
          body: |
            Guten Nachmittag,

            hier die Parkbelegung an der P+R-Anlage Ohlsdorf:

            – Um 15:01 Uhr: ${{ steps.load.outputs.free_530 }} freie Plätze
            – Um 15:02 Uhr: ${{ steps.load.outputs.free_600 }} freie Plätze
            – Um 15:03 Uhr: ${{ steps.load.outputs.free_630 }} freie Plätze

            Viele Grüße!

      - name: Lösche temporäre Dateien
        run: rm 1501.txt 1502.txt 1503.txt
